In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime
pd.set_option("display.max_columns",None)

In [2]:
df = pd.read_csv(r"F:\Education and Job\Guvi\Placement prep projects\Horse_Race_Prediction\Combined_data\combined_horse_race_data.csv")

df.head(4)

C:\Users\91843\AppData\Local\Temp\ipykernel_11400\2703212855.py:1: DtypeWarning: Columns (27,32,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"F:\Education and Job\Guvi\Placement prep projects\Horse_Race_Prediction\Combined_data\combined_horse_race_data.csv")


rid         horseName  age  saddle  decimalPrice  isFav  \
0  271018        Combermere  6.0     0.0      0.222222      0   
1  271018     Royal Battery  6.0     0.0      0.090909      0   
2  271018           Just So  7.0     0.0      0.029412      0   
3  271018  Mandraki Shuffle  8.0     0.0      0.090909      0   

       trainerName  jockeyName  position positionL  dist  weightSt  weightLb  \
0        R G Frost     J Frost         1       NaN   NaN        11         0   
1       D H Barons     S Earle         2        10   NaN        11         0   
2      J D Roberts  S Burrough         3        15  25.0        10         7   
3  Oliver Sherwood  M Richards         4        20  45.0        11         0   

   overWeight  outHandicap headGear    RPR    TR  OR       father  \
0         NaN          NaN      NaN  111.0  94.0 NaN      Absalom   
1         NaN          NaN      NaN  101.0  88.0 NaN  Norfolk Air   
2         NaN          NaN      NaN   86.0  71.0 NaN        Sousa   
3         NaN          NaN        b   66.0  65.0 NaN     Mandalus   

           mother         gfather  runners    margin  weight  res_win  \
0  Queen's Parade  Sovereign Path       14  1.521003      69      1.0   
1      All At Sea    Man The Rail       14  1.521003      69      0.0   
2    Just Camilla     Ascertain I       14  1.521003      66      0.0   
3      Indictment     Desert Call       14  1.521003      69      0.0   

   res_place price  course   time      date  \
0        1.0   NaN  Exeter  03:15  90/01/01   
1        1.0   NaN  Exeter  03:15  90/01/01   
2        1.0   NaN  Exeter  03:15  90/01/01   
3        0.0   NaN  Exeter  03:15  90/01/01   

                                               title rclass band   ages  \
0  David Garrett Memorial Challenge Trophy Novice...    NaN  NaN  6-8yo   
1  David Garrett Memorial Challenge Trophy Novice...    NaN  NaN  6-8yo   
2  David Garrett Memorial Challenge Trophy Novice...    NaN  NaN  6-8yo   
3  David Garrett Memorial Challenge Trophy Novice...    NaN  NaN  6-8yo   

  distance condition    hurdles                         prizes  winningTime  \
0     3m1f      Soft  19 fences  [2922.5, 875.0, 420.0, 192.5]        398.3   
1     3m1f      Soft  19 fences  [2922.5, 875.0, 420.0, 192.5]        398.3   
2     3m1f      Soft  19 fences  [2922.5, 875.0, 420.0, 192.5]        398.3   
3     3m1f      Soft  19 fences  [2922.5, 875.0, 420.0, 192.5]        398.3   

    prize  metric countryCode ncond  class currency  
0  4409.0  5028.0          GB     5      0      NaN  
1  4409.0  5028.0          GB     5      0      NaN  
2  4409.0  5028.0          GB     5      0      NaN  
3  4409.0  5028.0          GB     5      0      NaN

In [3]:
df.shape

(4107315, 46)

In [4]:
df.columns

Index(['rid', 'horseName', 'age', 'saddle', 'decimalPrice', 'isFav',
       'trainerName', 'jockeyName', 'position', 'positionL', 'dist',
       'weightSt', 'weightLb', 'overWeight', 'outHandicap', 'headGear', 'RPR',
       'TR', 'OR', 'father', 'mother', 'gfather', 'runners', 'margin',
       'weight', 'res_win', 'res_place', 'price', 'course', 'time', 'date',
       'title', 'rclass', 'band', 'ages', 'distance', 'condition', 'hurdles',
       'prizes', 'winningTime', 'prize', 'metric', 'countryCode', 'ncond',
       'class', 'currency'],
      dtype='object')

In [5]:
df['distance'].unique()

array(['3m1f', '2m', '1m7½f', '2m6f', '2m1f', '6f', '3m1½f', '1m', '2m2f',
       '3m', '2m3f', '2m4f', '7f', '1m3f', '2m4½f', '4m', '3m½f', '1m6f',
       '1m4f', '3m2½f', '2m5f', '1m2f', '3m4f', '2m3½f', '2m½f', '2m7f',
       '3m2f', '5f', '3m5f', '2m5½f', '3m6f', '1m5f', '2m7½f', '2m1½f',
       '2m6½f', '4m½f', '2m2½f', '3m3f', '1m6½f', '1m1f', '1m4½f', '7½f',
       '1m½f', '1m7f', '5½f', '4m4f', '1m2½f', '1m5½f', '4m2f', '1m3½f',
       '1m1½f', '6½f', '3m3½f', '4m2½f', '4m3f', '3m4½f', '3m5½f', '4m1f',
       '3m7f', '4m1½f', '3m6½f', '3m7½f', '4f', '4½f', '4m4½f'],
      dtype=object)

In [6]:
df['isFav'].unique()

array([0, 1])

In [7]:
df['runners'].value_counts()

runners
12    378048
10    362370
11    356389
9     343566
14    329686
13    320593
8     313384
16    259486
7     256382
15    246480
6     186582
18    142920
17    131138
5     110645
20     85760
19     69711
4      49140
22     30184
21     27027
23     19136
24     19008
25     15875
3      12249
27      8100
28      7784
29      7424
26      6786
30      6690
2       1346
40       760
32       672
31       527
33       396
34       374
35       210
36       180
39       156
38       114
37        37
Name: count, dtype: int64

In [8]:
df['res_win'].unique()

array([1., 0.])

In [9]:
df['res_place'].unique()

array([1., 0.])

In [10]:
df['position'].unique()

array([ 1,  2,  3,  4,  5,  6, 40,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39,  0])

In [11]:
df.isnull().sum()

rid                   0
horseName             0
age                 309
saddle           179168
decimalPrice          0
isFav                 0
trainerName        2850
jockeyName          125
position              0
positionL        783662
dist            1074385
weightSt              0
weightLb              0
overWeight      4012988
outHandicap     3994332
headGear        3119695
RPR              864877
TR              1681610
OR              1795263
father             1289
mother             4480
gfather          119374
runners               0
margin                0
weight                0
res_win               0
res_place             0
price           4012304
course                0
time                  0
date                  0
title                 7
rclass          1717422
band            2379862
ages             143485
distance              0
condition           404
hurdles         2880705
prizes                0
winningTime           0
prize            235284
metric          

In [12]:
df['course'].unique()

array(['Exeter', 'Tramore (IRE)', 'Catterick', 'Cheltenham', 'Windsor',
       'Leicester', 'Southwell (AW)', 'Fairyhouse (IRE)', 'Ayr',
       'Sedgefield', 'Lingfield (AW)', 'Thurles (IRE)', 'Nottingham',
       'Haydock', 'Musselburgh', 'Folkestone', 'Market Rasen',
       'Naas (IRE)', 'Sandown', 'Chepstow', 'Wolverhampton',
       'Newton Abbot', 'Plumpton', 'Kelso', 'Punchestown (IRE)',
       'Wincanton', 'Ascot', 'Wetherby', 'Leopardstown (IRE)',
       'Newcastle', 'Warwick', 'Fontwell', 'Carlisle', 'Worcester',
       'Ludlow', 'Gowran Park (IRE)', 'Kempton', 'Towcester',
       'Navan (IRE)', 'Doncaster', 'Clonmel (IRE)', 'Newbury',
       'Uttoxeter', 'Down Royal (IRE)', 'Fakenham', 'Huntingdon',
       'Downpatrick (IRE)', 'Tipperary (IRE)', 'Stratford', 'Hereford',
       'Wexford (RH) (IRE)', 'Bangor-on-Dee', 'Hexham', 'Limerick (IRE)',
       'Ballinrobe (IRE)', 'Taunton', 'Beverley', 'Curragh (IRE)',
       'Southwell', 'Roscommon (IRE)', 'Hamilton', 'Aintree', 'Bright

In [13]:
len(df['course'].unique())

440

In [14]:
selected_columns = ['horseName', 'age','trainerName', 'jockeyName','RPR','course',
                    'weight','TR','isFav', 'runners', 'distance','hurdles', 'res_place','position']
df_feature = df[selected_columns]


In [15]:
# Define the file path where you want to save the new CSV file
output_file = r"F:\Education and Job\Guvi\Placement prep projects\Horse_Race_Prediction\Combined_data\selected_features.csv"

# Save the dataframe to CSV
df_feature.to_csv(output_file, index=False)

print(f"DataFrame saved to {output_file}")


DataFrame saved to F:\Education and Job\Guvi\Placement prep projects\Horse_Race_Prediction\Combined_data\selected_features.csv
